// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function getFibonacciSequence(endNum){
  var sequence = [1];
  var currentNum = sequence[sequence.length - 1];
  while(currentNum <= endNum){
    var previousNum = sequence[sequence.length - 2] || 0;
    currentNum = currentNum + previousNum;
    if(currentNum <= endNum)
      sequence.push(currentNum);
  }
  return sequence;
}

function addEvenNumbers(arr){
  var sum = 0;
  arr.forEach(function(num){
    if(num % 2 == 0){
      sum += num;
    }
  });
  return sum;
}

var seq = getFibonacciSequence(4000000);
var sum = addEvenNumbers(seq);
console.log(sum);
